spring:
  application:
    name: "Spring-HW-3"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
  # консоль отладки
  h2:
    console:
      enabled: true
      path: /h2-console

  # swagger
  springdoc:
    show-actuator: false
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
